config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'products' => 'products#index'
  get "products/new" => "products#new", as: :new_product
  get "products/:name" => "products#show", as: :product 
  post "products" => "products#create"
  get "products/:name/edit" => "products#edit", as: :edit_product
  patch "products/:id" => "products#update"
  delete "products/:id" => "products#destroy"

  get "users" => "users#index"
  get "users/new" => "users#new" 
  post "users" => "users#create"
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'products/:product_id/comments' => 'comments#index', as: :product_comments
  post 'products/:product_id/comments' => 'comments#create'
  get 'products/:product_id/comments/new' => 'comments#new', as: :new_product_comment
  get 'products/:product_id/comments/:id/edit' => 'comments#edit', as: :edit_product_comment
  get 'products/:product_id/comments/:id' => 'comments#show', as: :product_comment
  patch 'products/:product_id/comments/:id' => 'comments#update'
  put 'products/:product_id/comments/:id' => 'comments#update'
  delete 'products/:product_id/comments/:id' => 'comments#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product

   validates :body, presence: true, length: { minimum: 5 }
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { small: "300x200", med: "600x400", large: "1200x800" }
	 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	 has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/models/weather_lookup.rb
# class WeatherLookup
# 	attr_accessor :temperature, :icon
# 	def fetch_weather
# 		HTTParty.get("http://api.wunderground.com/api/67be5ea9d5581cec/hourly/q/90266.xml")
# 	end
	
# 	def initialize
# 		weather_hash = fetch_weather
# 		assign_values(weather_hash)
# 	end

# 	def assign_values(weather_hash)
# 		 hourly_forecast_response = weather_hash.parsed_response['response']['hourly_forecast']['forecast'].first
#       # self.temperature = hourly_forecast_response['temp']['english']
#       self.icon = hourly_forecast_response['icon_url']
#     end

#     def home
#     @weather_lookup = WeatherLookup.new
# 	end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    redirect_to product_path(@product.name)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_path(@product.name) 
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find_by(name: params[:name])
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(params.require(:product).permit(:name, :price, :weight, :inventory, :description, :category, :image))
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def edit
		@product = Product.find_by(name: params[:name])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params.require(:product).permit(:name, :price, :weight, :inventory, :description, :category, :image))
			redirect_to product_path(@product.name)
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path 
	end

	private
  	def post_params
    params.require(:product).permit(:name, :description, :image)

  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      # make a new key in our session object called :user_id
      # which gets stored in a cookie in our browser
      session[:user_id] = user.id.to_s
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
  	session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	 def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to products_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :zip, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	  def current_user
	  @current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="row">
<p>
  <div class="col-md-12"><strong>Name:</strong>
  <%= comment.commenter %></div>
</p>
 
<p>
  <div class="col-md-12"><strong>Comment:</strong>
  <%= comment.body %></div>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.product, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-12"><%= form_for([@product, @product.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunglassesProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>


<div class="container-fluid">    
    <!-- Second navbar for sign in -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> 
          <%= link_to( image_tag("logo-sun.png", size: "50x50"), products_path) %>
          <a class="navbar-brand" href="#"><!--Website Name--></a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sport", product_path(:Sport), :class => "btn btn-default btn-outline btn-circle collapsed", :id => "header-button" %></li>
            <li><%= link_to "Retro", product_path(:Retro), :class => "btn btn-default btn-outline btn-circle collapsed", :id => "header-button" %></li>
            <li><%= link_to "Wild", product_path(:Wild), :class => "btn btn-default btn-outline btn-circle collapsed", :id => "header-button" %></li>
            


            <li>
             <%= link_to "Login", login_path, :class => "btn btn-default btn-outline btn-circle collapsed", :id => "header-button"  %>
            </li>
            <li><%= link_to "Sign Up", users_new_path, :class => "btn btn-default btn-outline btn-circle collapsed", :id => "header-button"  %></li>
            <li><% if current_user %><%= link_to 'Log Out', logout_path, method: :delete, :class => "btn btn-default btn-sm btn-outline btn-circle collapsed" %></li>
            <li><small>Logged in as:<br><%= current_user.name %></small></li><% end %>

             

              
          </ul>
        
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
            <form class="navbar-form navbar-right form-inline" role="form">
              <div class="form-group">
             
                <label class="sr-only" for="Email">Email</label>
                
                <input type="email" class="form-control" id="email-login" placeholder="Email" autofocus required />
              </div>
              <div class="form-group">
              
                <label class="sr-only" for="Password">Password</label>
                <input type="password" class="form-control" id="password-login" placeholder="Password" required />
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form>
          </div>
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-search">
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" />
              </div>
              <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </form>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
</div><!-- /.container-fluid -->

<strong>New update</strong>



<%= yield %>



</body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :price %>
	<%= f.text_field :price %>
</div>

<div>
	<%= f.label :weight %>
	<%= f.text_field :weight %>
</div>

<div>
	<%= f.label :inventory %>
	<%= f.text_field :inventory %>
</div>

<div>
	<%= f.label :description %>
	<%= f.text_field :description %>
</div>

<div>
	<%= f.label :category %>
	<%= f.text_field :category %>
</div>

<div>
	<%= f.label :image %>
	<%= f.file_field :image %>
</div>


<%= f.submit "Submit Changes" %>

<% end %>

<br>

<%= link_to "Back to Product List", products_path(@product) %>

<%= link_to "Delete This Product", product_path(@product), method: :delete, data: { confirm: "Are you sure you want to delete this product?"} %> 

app/views/products/index.html.erb
<h1>Welcome to Sunglasses For Days</h1><h2><%= current_user.name if current_user%></h2> 

<% 
if @current_user
@url = "http://api.wunderground.com/api/67be5ea9d5581cec/geolookup/conditions/q/#{current_user.zip}.json"
require 'open-uri'

require 'json'
open(@url) do |f|
  json_string = f.read
  parsed_json = JSON.parse(json_string)
  @location = parsed_json['location']['city']
  @temp_f = parsed_json['current_observation']['temp_f']
  @icon = parsed_json['current_observation']['icon_url']
 end

end
%>

<div class="row">
  <div class="col-md-12"><%= @location %></div>

  <div><%= @temp_f %></div>
  <div><%= image_tag "#{@icon}" %></div>
</div>





<div class="row">
  <div class="col-md-12"><h2></h2></div>
        <% @products.each do |product| %>
              <div class="col-md-12"><h3><%= product.name %></h3></div>
              <div class="col-md-12"><% product.price %></div>
              <div class="col-md-12"><% product.description %></div>
              <div class="col-md-12"><%= link_to "#{"View the " + product.name + " Sunglasses"}", product_path(product.name) %></div>
              <div><% link_to "Delete This Product", product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete this product?"} %></div>
              <div class="col-md-12 grow"><%= image_tag product.image.url(:large) %></div>


<% end %>

<div class="row">
  <div class="col-md-12"><%= image_tag("sun.jpg", class: "sun-spin sun-shrink") %></div> 
</div>

<br>
	<div class="btn btn-success"><%= link_to "Add Product", new_product_path %></div>

	<div class="btn btn-info"><%= link_to 'Log Out', logout_path, method: :delete %></div>
<br>
<br>

app/views/products/new.html.erb
<%= form_for @product do |f| %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :price %>
	<%= f.text_field :price %>
</div>

<div>
	<%= f.label :weight %>
	<%= f.text_field :weight %>
</div>

<div>
	<%= f.label :inventory %>
	<%= f.text_field :inventory %>
</div>

<div>
	<%= f.label :description %>
	<%= f.text_field :description %>
</div>

<div>
	<%= f.label :category %>
	<%= f.text_field :category %>
</div>

<div>
	<%= f.label :image %>
	<%= f.file_field :image %>
</div>


<%= f.submit "Add New Product" %>

<% end %>

<br>

<%= link_to "Back to Product List", products_path %>

app/views/products/show.html.erb
<div class="row top-row">
  <div class="col-md-12"><h1>The <%= @product.name %> Sunglasses</h1></div>
  <br>
</div>


<div class="row show-box">

   <div class="col-md-12 grow"><%= image_tag @product.image.url(:large) %></div>
	  <br>
	  <br>
      	<div class="price-box">

	      <div class="col-md-4"><h3>Price: $<%= @product.price %></h3></div>
	      <div class="col-md-4"><% @product.weight %></div>
	      <div class="col-md-4"><% @product.inventory %></div>
	      <div class="col-md-4"><%= @product.description %></div>
	      <div class="col-md-4"><%= @product.category %></div>
		</div>
</div>



<!-- This is my comments view section -->


<!-- This is my comments view section -->
<br>
<div class="row">

	<div class="col-md-12"><h2>Add a comment:</h2></div>

		<%= render 'comments/form' %>
	
	    	<div class="col-md-12"><%= render @product.comments %></div>
	 
	 		

		<br>
 
	<%#= link_to 'Edit', edit_product_path(@product.name) %> 
	
</div>

<div class="row">
	<div class="btn btn-default"><%= link_to 'Back To All Products', products_path %></div>
	<div class="btn btn-success button-text"><%= link_to 'Edit', edit_product_path(@product.name) %></div>        
	<div class="btn btn-danger"><%= link_to "Delete This Product", product_path(@product), method: :delete, data: { confirm: "Are you sure you want to delete this product?"} %> </div>
</div>


  
    

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

<%#= link_to 'Log Out', logout_path, method: :delete %>

app/views/users/new.html.erb
<br>
<br>
<br>
<br>
<%= form_for @user do |f| %>
<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Sign Up To Sunglasses For Days<small></small></h3>
            </div>
            <div class="panel-body">
              <form role="form">
                <div class="row">
                  <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                    <!-- This is my bootstrap form field for Name -->
                    <%= f.text_field :name, placeholder: "Name", :class => "form-control input-sm", id: "name", :required => true %>
                    </div>
                  </div>
                  <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                    <!-- This is my bootstrap form field for Name -->
                    <%= f.text_field :zip, placeholder: "Zip Code", :class => "form-control input-sm", id: "zip", :required => true %>
                    </div>
                  </div>
                </div>

                    <!-- This is my bootstrap form field for email address -->
                <div class="form-group">
                <%= f.text_field :email, placeholder: "Email Address", :class => "form-control input-sm", id: "email", :required => true %>
                </div>
               
                <div class="row">
                  <div class="col-xs-6 col-sm-6 col-md-6">
                  <!-- This is my bootstrap form field for password -->
                    <div class="form-group">
                    <%= f.password_field :password, placeholder: "Password", :class => "form-control input-sm", id: "password_confirmation", :required => true %>
                    </div>
                  </div>
                  <div class="col-xs-6 col-sm-6 col-md-6">
                  <!-- This is my bootstrap form field for confirm password -->
                    <div class="form-group">
                    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", :class => "form-control input-sm", id: "password_confirmation", :required => true  %>
                    </div>
                  </div>
                </div>
                <!-- This is my bootstrap submit button for signing up -->
                 <%= f.submit :Submit, :class => "btn btn-info btn-block" %>
                
              
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>